// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ENGINE`, `EngineState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> startAudioSession({
  required String trackJson,
  double? startTime,
}) => RustLib.instance.api.crateMobileApiStartAudioSession(
  trackJson: trackJson,
  startTime: startTime,
);

Future<void> stopAudioSession() =>
    RustLib.instance.api.crateMobileApiStopAudioSession();

Future<void> pauseAudio() => RustLib.instance.api.crateMobileApiPauseAudio();

Future<void> resumeAudio() => RustLib.instance.api.crateMobileApiResumeAudio();

Future<void> setVolume({required double volume}) =>
    RustLib.instance.api.crateMobileApiSetVolume(volume: volume);

Future<void> updateSession({required String trackJson}) =>
    RustLib.instance.api.crateMobileApiUpdateSession(trackJson: trackJson);

Future<void> pushClipChunk({
  required BigInt index,
  required List<double> samples,
  required bool finished,
}) => RustLib.instance.api.crateMobileApiPushClipChunk(
  index: index,
  samples: samples,
  finished: finished,
);

Future<Float32List> generateWaveformSnippet({required double durationSec}) =>
    RustLib.instance.api.crateMobileApiGenerateWaveformSnippet(
      durationSec: durationSec,
    );
